### PR TITLE
Added Rx to Auth, Database, RemoteConfig and Storage.

### PR DESCRIPTION
**Pull request by neoplastic**
There are still tasks to be completed:
- Subspec RemoteConfig and Storage.
- Figure out the Cocoapods weak framework linking.

Some of these changes was to include 'Firebase/Auth' pod as that's pretty much required.

### CODE REVIEW

**Comment by popaaaandrei** [comment]
gg @neoplastic beautiful work

**Comment by popaaaandrei** [comment]
I was going to make a pull request but yours is much more elegant in every way

**Comment by hijamoya** [comment]
Are you plan to merge this? This is great!

**Comment by CezaryKopacz** [comment]
Any progress here?

**Comment by popaaaandrei** [comment]
@neoplastic just create your own fork and I'll help you with it. I had to change implementation for latest Firebase & Swift.

**Comment by neoplastic** [comment]
Wow. I haven't touched FB in a while. I'll look at forking and merge request this week. 

Been busy with contract work, not much time for personal RxFB :(

**Comment by neoplastic** [comment]
There's also a more elegant RxSwift 3 implementation to extend off 'Base' in which I should implement so you can .rx to access the extension functionality. 

Might need to write a Swift 2.3 and Swift 3.0 version.

**Comment by kzaher** [comment]
Hi @mbalex99 ,

I'm assuming you don't have time right now, so hope it's ok to help out with this since I need firebase integration at the moment :)

**Comment by mbalex99** [comment]
Wow everyone I'm so sorrry but for some reason I haven't gotten ANY notifications except for @kzaher's :-( 

Shame on me so sorry! I would have jumped on this when this PR happened

**Comment by kzaher** [comment]
@mbalex99 I'll make a new PR for 3.0 adaptations :)

I'm having issues with pods + firebase dependencies. Does anyone have any idea how we could solve that?

I can make other adaptations :)

**Comment by mbalex99** [comment]
@kzaher what specifically are you having issues with?

**Pull request merged**
